/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoggedOutRouteRouteImport } from './routes/_logged-out/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoggedOutLoginRouteImport } from './routes/_logged-out/login'
import { Route as LoggedOutRegisterIndexRouteImport } from './routes/_logged-out/register/index'
import { Route as LoggedOutRegisterWelcomeRouteImport } from './routes/_logged-out/register/welcome'
import { Route as LoggedOutRegisterInviteTeamRouteImport } from './routes/_logged-out/register/invite-team'
import { Route as LoggedOutRegisterIndividualRouteImport } from './routes/_logged-out/register/individual'
import { Route as LoggedOutRegisterCompleteProfileRouteImport } from './routes/_logged-out/register/complete-profile'

const LoggedOutRouteRoute = LoggedOutRouteRouteImport.update({
  id: '/_logged-out',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggedOutLoginRoute = LoggedOutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LoggedOutRouteRoute,
} as any)
const LoggedOutRegisterIndexRoute = LoggedOutRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => LoggedOutRouteRoute,
} as any)
const LoggedOutRegisterWelcomeRoute =
  LoggedOutRegisterWelcomeRouteImport.update({
    id: '/register/welcome',
    path: '/register/welcome',
    getParentRoute: () => LoggedOutRouteRoute,
  } as any)
const LoggedOutRegisterInviteTeamRoute =
  LoggedOutRegisterInviteTeamRouteImport.update({
    id: '/register/invite-team',
    path: '/register/invite-team',
    getParentRoute: () => LoggedOutRouteRoute,
  } as any)
const LoggedOutRegisterIndividualRoute =
  LoggedOutRegisterIndividualRouteImport.update({
    id: '/register/individual',
    path: '/register/individual',
    getParentRoute: () => LoggedOutRouteRoute,
  } as any)
const LoggedOutRegisterCompleteProfileRoute =
  LoggedOutRegisterCompleteProfileRouteImport.update({
    id: '/register/complete-profile',
    path: '/register/complete-profile',
    getParentRoute: () => LoggedOutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoggedOutLoginRoute
  '/register/complete-profile': typeof LoggedOutRegisterCompleteProfileRoute
  '/register/individual': typeof LoggedOutRegisterIndividualRoute
  '/register/invite-team': typeof LoggedOutRegisterInviteTeamRoute
  '/register/welcome': typeof LoggedOutRegisterWelcomeRoute
  '/register/': typeof LoggedOutRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoggedOutLoginRoute
  '/register/complete-profile': typeof LoggedOutRegisterCompleteProfileRoute
  '/register/individual': typeof LoggedOutRegisterIndividualRoute
  '/register/invite-team': typeof LoggedOutRegisterInviteTeamRoute
  '/register/welcome': typeof LoggedOutRegisterWelcomeRoute
  '/register': typeof LoggedOutRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_logged-out': typeof LoggedOutRouteRouteWithChildren
  '/_logged-out/login': typeof LoggedOutLoginRoute
  '/_logged-out/register/complete-profile': typeof LoggedOutRegisterCompleteProfileRoute
  '/_logged-out/register/individual': typeof LoggedOutRegisterIndividualRoute
  '/_logged-out/register/invite-team': typeof LoggedOutRegisterInviteTeamRoute
  '/_logged-out/register/welcome': typeof LoggedOutRegisterWelcomeRoute
  '/_logged-out/register/': typeof LoggedOutRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register/complete-profile'
    | '/register/individual'
    | '/register/invite-team'
    | '/register/welcome'
    | '/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register/complete-profile'
    | '/register/individual'
    | '/register/invite-team'
    | '/register/welcome'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/_logged-out'
    | '/_logged-out/login'
    | '/_logged-out/register/complete-profile'
    | '/_logged-out/register/individual'
    | '/_logged-out/register/invite-team'
    | '/_logged-out/register/welcome'
    | '/_logged-out/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoggedOutRouteRoute: typeof LoggedOutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_logged-out': {
      id: '/_logged-out'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LoggedOutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_logged-out/login': {
      id: '/_logged-out/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoggedOutLoginRouteImport
      parentRoute: typeof LoggedOutRouteRoute
    }
    '/_logged-out/register/': {
      id: '/_logged-out/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof LoggedOutRegisterIndexRouteImport
      parentRoute: typeof LoggedOutRouteRoute
    }
    '/_logged-out/register/welcome': {
      id: '/_logged-out/register/welcome'
      path: '/register/welcome'
      fullPath: '/register/welcome'
      preLoaderRoute: typeof LoggedOutRegisterWelcomeRouteImport
      parentRoute: typeof LoggedOutRouteRoute
    }
    '/_logged-out/register/invite-team': {
      id: '/_logged-out/register/invite-team'
      path: '/register/invite-team'
      fullPath: '/register/invite-team'
      preLoaderRoute: typeof LoggedOutRegisterInviteTeamRouteImport
      parentRoute: typeof LoggedOutRouteRoute
    }
    '/_logged-out/register/individual': {
      id: '/_logged-out/register/individual'
      path: '/register/individual'
      fullPath: '/register/individual'
      preLoaderRoute: typeof LoggedOutRegisterIndividualRouteImport
      parentRoute: typeof LoggedOutRouteRoute
    }
    '/_logged-out/register/complete-profile': {
      id: '/_logged-out/register/complete-profile'
      path: '/register/complete-profile'
      fullPath: '/register/complete-profile'
      preLoaderRoute: typeof LoggedOutRegisterCompleteProfileRouteImport
      parentRoute: typeof LoggedOutRouteRoute
    }
  }
}

interface LoggedOutRouteRouteChildren {
  LoggedOutLoginRoute: typeof LoggedOutLoginRoute
  LoggedOutRegisterCompleteProfileRoute: typeof LoggedOutRegisterCompleteProfileRoute
  LoggedOutRegisterIndividualRoute: typeof LoggedOutRegisterIndividualRoute
  LoggedOutRegisterInviteTeamRoute: typeof LoggedOutRegisterInviteTeamRoute
  LoggedOutRegisterWelcomeRoute: typeof LoggedOutRegisterWelcomeRoute
  LoggedOutRegisterIndexRoute: typeof LoggedOutRegisterIndexRoute
}

const LoggedOutRouteRouteChildren: LoggedOutRouteRouteChildren = {
  LoggedOutLoginRoute: LoggedOutLoginRoute,
  LoggedOutRegisterCompleteProfileRoute: LoggedOutRegisterCompleteProfileRoute,
  LoggedOutRegisterIndividualRoute: LoggedOutRegisterIndividualRoute,
  LoggedOutRegisterInviteTeamRoute: LoggedOutRegisterInviteTeamRoute,
  LoggedOutRegisterWelcomeRoute: LoggedOutRegisterWelcomeRoute,
  LoggedOutRegisterIndexRoute: LoggedOutRegisterIndexRoute,
}

const LoggedOutRouteRouteWithChildren = LoggedOutRouteRoute._addFileChildren(
  LoggedOutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoggedOutRouteRoute: LoggedOutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
